version: '2'
services:
  web:
    build: .
    links:
      - db
    volumes:
      - ./web/:/var/www/site/
    depends_on:
      - db
    extra_hosts:
      - "moneycheck.local:127.0.0.1"
  db:
    image: mysql/mysql-server:5.5
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "test"
volumes:
 mysql:
